name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install G++
      run: sudo apt-get install g++ -y
    - name: Compile main.cpp file
      run: g++ main.cpp -o main
    - name: Run compiled file
      run: ./main  
