name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ mesa-common-dev

      - name: Install aqtinstall
        run: python3 -m pip install aqtinstall

      - name: Install Qt
        run: python3 -m aqt install-qt linux desktop 5.15.2 --outputdir /opt/qt

      - name: Set QT_BASE_DIR environment variable
        run: echo "QT_BASE_DIR=/opt/qt/5.15.2/gcc_64" >> $GITHUB_ENV

      - name: Build myNotes
        run: |
          cd myNotes
          mkdir build
          cd build
          cmake -DQt5_DIR=$QT_BASE_DIR/lib/cmake/Qt5 ..
          make

      - name: Build myPencil
        run: |
          cd myPencil
          mkdir build
          cd build
          cmake -DQt5_DIR=$QT_BASE_DIR/lib/cmake/Qt5 ..
          make
