name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3.3.0

      - name: Install G++
        run: sudo apt-get install g++ -y

      - name: Compile main.cpp file
        run: g++ main.cpp -o qtwmain

      - name: Run Qt Widgets compiled file
        run: ./qtwmain

      - name: Run QML file
        run: qmlscene main.qml
